# o2-scalpel - top-level Makefile.
#
# Stage 1I targets: regenerate plugin trees, restamp banners, run uvx smoke.
# Stage 1J seeded the original generate-plugins target; Stage 1I extends it
# with banner restamping + the verify-plugins-fresh smoke driver.
#
# Override OUT to write the trees somewhere other than the repo root, and
# LANGUAGES to limit the run (e.g. ``make generate-plugins LANGUAGES=rust``).

SHELL := /bin/bash

.PHONY: help generate-plugins generate-rust generate-python generate-markdown verify-plugins-fresh _restamp-banners e2e-playground

OUT ?= .
LANGUAGES ?= rust python markdown

PYBIN := vendor/serena/.venv/bin
GEN := PATH="$(PYBIN):$$PATH" o2-scalpel-newplugin

help:
	@echo "Targets:"
	@echo "  generate-plugins      Regenerate o2-scalpel-<lang>/ trees + marketplace.json + restamp banners"
	@echo "  generate-rust         Single-language emit (rust)"
	@echo "  generate-python       Single-language emit (python)"
	@echo "  generate-markdown     Single-language emit (markdown)"
	@echo "  verify-plugins-fresh  Run scripts/stage_1i_uvx_smoke.sh against each tree"
	@echo "  e2e-playground        Run the v1.2.2 playground E2E suite (gated on rust-analyzer + cargo)"
	@echo ""
	@echo "Variables:"
	@echo "  OUT=$(OUT)             Output parent directory"
	@echo "  LANGUAGES='$(LANGUAGES)'  Languages to emit"

generate-plugins:
	@for lang in $(LANGUAGES); do \
	  $(PYBIN)/o2-scalpel-newplugin --language $$lang --out $(OUT) --force ; \
	done
	@$(PYBIN)/python -m serena.marketplace.build --root $(OUT) --write
	@$(MAKE) -s _restamp-banners
	@echo "Plugin trees regenerated. Review 'git diff o2-scalpel-*/ marketplace.json' before commit."

generate-rust:
	@echo "[generate] o2-scalpel-rust/"
	$(GEN) --language rust --out $(OUT) --force

generate-python:
	@echo "[generate] o2-scalpel-python/"
	$(GEN) --language python --out $(OUT) --force

generate-markdown:
	@echo "[generate] o2-scalpel-markdown/"
	$(GEN) --language markdown --out $(OUT) --force

# Internal: re-stamp the do-not-hand-edit banner across the generated JSON files.
_restamp-banners:
	@GEN_SHA=$$(cd vendor/serena && git rev-parse HEAD); \
	for f in $(OUT)/o2-scalpel-rust/.claude-plugin/plugin.json $(OUT)/o2-scalpel-rust/.mcp.json \
	         $(OUT)/o2-scalpel-python/.claude-plugin/plugin.json $(OUT)/o2-scalpel-python/.mcp.json \
	         $(OUT)/o2-scalpel-markdown/.claude-plugin/plugin.json $(OUT)/o2-scalpel-markdown/.mcp.json; do \
	  if [ ! -f $$f ]; then continue; fi; \
	  python3 -c "import json,sys; d=json.load(open(sys.argv[1])); d.pop('_generator',None); b='Generated by o2-scalpel-newplugin - do NOT hand-edit. Regenerate via make generate-plugins (generator @ '+sys.argv[2][:12]+').'; nd={'_generator': b, **d}; open(sys.argv[1],'w').write(json.dumps(nd,indent=2,sort_keys=True,ensure_ascii=False)+chr(10))" $$f $$GEN_SHA; \
	done

verify-plugins-fresh:
	@scripts/stage_1i_uvx_smoke.sh rust
	@scripts/stage_1i_uvx_smoke.sh python

e2e-playground:
	@bash scripts/e2e_playground.sh
